# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x07user.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12#\n\x06status\x18\x04 \x01(\x0e\x32\x13.user.v2.UserStatus\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampJ\x04\x08\x07\x10\x08R\tfull_name\"8\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\"1\n\x12\x43reateUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v2.User\"=\n\x0eGetUserRequest\x12\x0c\n\x02id\x18\x01 \x01(\tH\x00\x12\x0f\n\x05\x65mail\x18\x02 \x01(\tH\x00\x42\x0c\n\nidentifier\".\n\x0fGetUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v2.User\"#\n\x15\x44\x65\x61\x63tivateUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"5\n\x16\x44\x65\x61\x63tivateUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v2.User*F\n\nUserStatus\x12\x1b\n\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0f\n\x0b\x44\x45\x41\x43TIVATED\x10\x02\x32\xe7\x01\n\rUserServiceV2\x12\x45\n\nCreateUser\x12\x1a.user.v2.CreateUserRequest\x1a\x1b.user.v2.CreateUserResponse\x12<\n\x07GetUser\x12\x17.user.v2.GetUserRequest\x1a\x18.user.v2.GetUserResponse\x12Q\n\x0e\x44\x65\x61\x63tivateUser\x12\x1e.user.v2.DeactivateUserRequest\x1a\x1f.user.v2.DeactivateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERSTATUS']._serialized_start=576
  _globals['_USERSTATUS']._serialized_end=646
  _globals['_USER']._serialized_start=57
  _globals['_USER']._serialized_end=262
  _globals['_CREATEUSERREQUEST']._serialized_start=264
  _globals['_CREATEUSERREQUEST']._serialized_end=320
  _globals['_CREATEUSERRESPONSE']._serialized_start=322
  _globals['_CREATEUSERRESPONSE']._serialized_end=371
  _globals['_GETUSERREQUEST']._serialized_start=373
  _globals['_GETUSERREQUEST']._serialized_end=434
  _globals['_GETUSERRESPONSE']._serialized_start=436
  _globals['_GETUSERRESPONSE']._serialized_end=482
  _globals['_DEACTIVATEUSERREQUEST']._serialized_start=484
  _globals['_DEACTIVATEUSERREQUEST']._serialized_end=519
  _globals['_DEACTIVATEUSERRESPONSE']._serialized_start=521
  _globals['_DEACTIVATEUSERRESPONSE']._serialized_end=574
  _globals['_USERSERVICEV2']._serialized_start=649
  _globals['_USERSERVICEV2']._serialized_end=880
# @@protoc_insertion_point(module_scope)
