# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x07user.v1\"[\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12#\n\x06status\x18\x04 \x01(\x0e\x32\x13.user.v1.UserStatus\"5\n\x11\x43reateUserRequest\x12\x11\n\tfull_name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"1\n\x12\x43reateUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v1.User\"\x1e\n\x0eGetUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\".\n\x0fGetUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v1.User\"%\n\x15\x44\x65\x61\x63tivateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"5\n\x16\x44\x65\x61\x63tivateUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v1.User*F\n\nUserStatus\x12\x1b\n\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0f\n\x0b\x44\x45\x41\x43TIVATED\x10\x02\x32\xe5\x01\n\x0bUserService\x12\x45\n\nCreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\x1b.user.v1.CreateUserResponse\x12<\n\x07GetUser\x12\x17.user.v1.GetUserRequest\x1a\x18.user.v1.GetUserResponse\x12Q\n\x0e\x44\x65\x61\x63tivateUser\x12\x1e.user.v1.DeactivateUserRequest\x1a\x1f.user.v1.DeactivateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERSTATUS']._serialized_start=396
  _globals['_USERSTATUS']._serialized_end=466
  _globals['_USER']._serialized_start=23
  _globals['_USER']._serialized_end=114
  _globals['_CREATEUSERREQUEST']._serialized_start=116
  _globals['_CREATEUSERREQUEST']._serialized_end=169
  _globals['_CREATEUSERRESPONSE']._serialized_start=171
  _globals['_CREATEUSERRESPONSE']._serialized_end=220
  _globals['_GETUSERREQUEST']._serialized_start=222
  _globals['_GETUSERREQUEST']._serialized_end=252
  _globals['_GETUSERRESPONSE']._serialized_start=254
  _globals['_GETUSERRESPONSE']._serialized_end=300
  _globals['_DEACTIVATEUSERREQUEST']._serialized_start=302
  _globals['_DEACTIVATEUSERREQUEST']._serialized_end=339
  _globals['_DEACTIVATEUSERRESPONSE']._serialized_start=341
  _globals['_DEACTIVATEUSERRESPONSE']._serialized_end=394
  _globals['_USERSERVICE']._serialized_start=469
  _globals['_USERSERVICE']._serialized_end=698
# @@protoc_insertion_point(module_scope)
